### ISSUE TITLE
Borderlands 1 Split Screen Problem

### ISSUE THREAD

**Issue by jonetiz** [lucasassislar/nucleuscoop#18] opened 2016-06-14 18:52 UTC
Okay, when I try to do split screen with 1 keyboard and 1 controller, the controller and keyboard only work on the screen being focused on. Help?

**Comment by lucasassislar** [comment] 2016-06-18 02:04
I kinda implemented without further testing, I'm going to test and see if I can fix it. Thanks for the heads up.

**Comment by lucasassislar** [comment] 2016-06-19 05:51
I messed up on the options being carried into the Game Handler, basically it was always starting without a keyboard player.
But still, Borderlands 1 is not responding to input when out of focus. On 2 and PreSequel I used -AlwaysFocus to fix that, but that command doesnt seem to work. I'm researching to see how to fix this last step.

**Comment by mirh** [comment] 2017-01-08 18:39
Seems like [ahk](https://www.reddit.com/r/Borderlands/comments/4e9d82/bl1_split_screen_pc_alwaysfocus_doesnt_work/) can do it. 
But tbh this seems a duplicate of #42

**Closed** 2022-09-17 08:53 UTC
